export enum WebSocketEvents {
  // User activity
  TYPING_STOP = "TYPING_STOP",
  TYPING_START = "TYPING_START",
  USER_ONLINE = "USER_ONLINE",
  USER_OFFLINE = "USER_OFFLINE",

  // Messages
  NEW_MESSAGE = "NEW_MESSAGE",
  MESSAGE_EDITED = "MESSAGE_EDITED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_DELIVERED = "MESSAGE_DELIVERED",
  MESSAGE_SEEN = "MESSAGE_SEEN",

  // Errors / system
  ERROR = "ERROR",
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  RECONNECTING = "RECONNECTING",
}